name: Continuous update

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  continuous-update:
    name: Continuous update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: NasuTek/boot2docker/checkout@dev
      - name: Update Dockerfile
        run: ./update.sh
      - name: Create Token
        id: token
        uses: NasuTek/boot2docker/create/token@dev
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: NasuTek/boot2docker/create/pull-request@dev
        with:
          token: ${{ steps.token.outputs.token }}
