name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
      name: Create release
      runs-on: ubuntu-22.04
      permissions:
        contents: write
      steps:
        - name: Create release
          uses: softprops/action-gh-release@v1
          with:
            name: Release ${{ github.ref_name }}
  release-package:
    name: ISO image
    needs: create-release
    permissions:
      contents: write
    uses: ./.github/workflows/release-image.yaml
