name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Create release
    permissions:
      contents: write
    uses: NasuTek/boot2docker/.github/workflows/create-release.yaml@dev

  release-package:
    name: ISO image
    needs: create-release
    permissions:
      contents: write
    uses: ./.github/workflows/release-image.yaml
